In [1]:
import pandas as pd
from scipy.io import arff
import numpy as np
from scipy import stats
import tensorflow as tf

from tensorflow.keras import Sequential, Model
from tensorflow.keras.layers import Dense, Input, Dropout
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import f1_score, accuracy_score, matthews_corrcoef

from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
import time
from tensorflow.keras.utils import to_categorical

import erlc as e
import dataPipeline as dp
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataPipeline = dp.DataPipeline()
erlc = e.ERLC()

In [3]:
data = dataPipeline.loadData(num_sets = 15)
data.head()

Loading dataset #1
Loading dataset #2
Loading dataset #3
Loading dataset #4
Loading dataset #5
Loading dataset #6
Loading dataset #7
Loading dataset #8
Loading dataset #9
Loading dataset #10
Loading dataset #11
Loading dataset #12
Loading dataset #13
Loading dataset #14
Loading dataset #15
Finished Loading. Final Size = (78377, 129)


R1-PA1:VH     R1-PM1:V  R1-PA2:VH     R1-PM2:V   R1-PA3:VH     R1-PM3:V  \
0  70.399324  127673.0908 -49.572308  127648.0176 -169.578319  127723.2374   
1  73.688102  130280.7109 -46.300719  130255.6377 -166.278082  130355.9307   
2  73.733939  130305.7842 -46.254883  130280.7109 -166.232245  130381.0040   
3  74.083443  130581.5902 -45.899649  130556.5169 -165.882741  130656.8100   
4  74.553268  131083.0556 -45.424094  131057.9823 -165.424375  131158.2754   

   R1-PA4:IH   R1-PM4:I  R1-PA5:IH   R1-PM5:I  ...  control_panel_log4  \
0  65.689611  605.91099 -57.003571  626.78553  ...                 0.0   
1  71.831719  483.59351 -50.947407  500.98896  ...                 0.0   
2  71.808800  483.59351 -50.913030  500.98896  ...                 0.0   
3  72.152575  482.86107 -50.437475  499.15786  ...                 0.0   
4  72.118198  484.50906 -50.013486  497.69298  ...                 0.0   

   relay1_log  relay2_log  relay3_log  relay4_log  snort_log1  snort_log2  \
0         0.0         0.0         0.0         0.0         0.0         0.0   
1         0.0         0.0         0.0         0.0         0.0         0.0   
2         0.0         0.0         0.0         0.0         0.0         0.0   
3         0.0         0.0         0.0         0.0         0.0         0.0   
4         0.0         0.0         0.0         0.0         0.0         0.0   

   snort_log3  snort_log4  marker  
0         0.0         0.0   b'41'  
1         0.0         0.0   b'41'  
2         0.0         0.0   b'41'  
3         0.0         0.0   b'41'  
4         0.0         0.0   b'41'  

[5 rows x 129 columns]

In [4]:
X, y = dataPipeline.dataProc(data)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
erlc.getLocalizationStats(X_train, y_train)

In [6]:
p_diff = erlc.getAveragePDforEachAttack(X_test, y_test)

Iteration i = 1
p_diff_temp shape = (117, 315)
p_diff_avg shape = (117,)
Iteration i = 2
p_diff_temp shape = (117, 341)
p_diff_avg shape = (117,)
Iteration i = 3
p_diff_temp shape = (117, 396)
p_diff_avg shape = (117,)
Iteration i = 4
p_diff_temp shape = (117, 601)
p_diff_avg shape = (117,)
Iteration i = 5
p_diff_temp shape = (117, 624)
p_diff_avg shape = (117,)
Iteration i = 6
p_diff_temp shape = (117, 688)
p_diff_avg shape = (117,)
Iteration i = 7
p_diff_temp shape = (117, 283)
p_diff_avg shape = (117,)
Iteration i = 8
p_diff_temp shape = (117, 252)
p_diff_avg shape = (117,)
Iteration i = 9
p_diff_temp shape = (117, 251)
p_diff_avg shape = (117,)
Iteration i = 10
p_diff_temp shape = (117, 358)
p_diff_avg shape = (117,)
Iteration i = 11
p_diff_temp shape = (117, 368)
p_diff_avg shape = (117,)
Iteration i = 12
p_diff_temp shape = (117, 396)
p_diff_avg shape = (117,)
Iteration i = 13
p_diff_temp shape = (117, 310)
p_diff_avg shape = (117,)
Iteration i = 14
p_diff_temp shape = (117, 353)

In [7]:
erlc.normal_means.shape

(117,)

In [8]:
p_diff.shape

(37, 117)

In [9]:
plt.figure(figsize=(10,20))
x_axis_labels = np.unique(y_test)
y_axis_labels = dataPipeline.getFeatureLabels(data)
sns.heatmap(np.transpose(p_diff), xticklabels=x_axis_labels, yticklabels=y_axis_labels)

In [10]:
maxes = []
for i in range(p_diff.shape[0]):
#     max_temp = np.where(p_diff[i] == np.max(p_diff[i]))
    temp = np.copy(p_diff[i])
#     temp[::-1].sort()

    max_temp = np.where(p_diff[i] > 0.8)

    print("Attack {}: ".format(i))
    print(max_temp)
    

Attack 0: 
(array([  2,   4,   6,  14,  15,  16,  17,  18,  21,  22,  24,  25,  26,
        27,  28,  29,  31,  44,  45,  46,  47,  51,  53,  54,  55,  58,
        60,  64,  72,  73,  74,  75,  76,  80,  82,  83,  84,  87,  89,
        91,  93, 101, 102, 103, 104, 105, 108, 109, 111, 112, 113, 114,
       115, 116]),)
Attack 1: 
(array([  2,   4,   6,  14,  15,  16,  17,  18,  22,  24,  25,  26,  28,
        29,  44,  45,  46,  47,  51,  53,  54,  55,  56,  58,  60,  73,
        74,  75,  76,  80,  82,  83,  84,  85,  87,  89,  91,  93, 101,
       102, 103, 104, 105, 109, 111, 112, 113, 114, 115, 116]),)
Attack 2: 
(array([  2,  14,  15,  16,  17,  18,  22,  24,  25,  26,  28,  29,  44,
        45,  46,  47,  51,  53,  54,  55,  58,  60,  64,  73,  74,  75,
        76,  80,  82,  83,  84,  87,  89,  91,  93, 101, 102, 103, 104,
       105, 109, 111, 112, 113, 114, 116]),)
Attack 3: 
(array([  2,   4,   6,  10,  14,  15,  16,  17,  18,  21,  22,  24,  25,
        26,  27,  29,  33,  35

In [11]:
X[:,1].shape

(78377,)